### PR TITLE
fix: gcp and aws exit code 1

### LINKED ISSUE #376: Cannot deploy AWS or GCP due to kubectl command failing in the API
> This issue was introduced by #363 

## The problem

When deploying Kubefirst to either AWS or GCP (may be other clouds - k3d and Civo are ok), there is an error `exiting with status 1` command that appears in the logs and we cannot proceed past that. After much code trawling, it appears that it is [this command](https://github.com/jokestax/kubefirst-api/blob/dfdee752a1d06107cbd86e61159dfe4cba7117c9/internal/controller/argocd.go#L202) that is failing.

The problem is that the mapping of the `/.k1` directory to the locally running `kubefirst-api` container is not the same across all cloud providers. This is likely due to authentication differences - eg, the EKS/GKE kubeconfigs require the AWS/GCP CLI whereas Civo is self-contained, with all the parameters in the kubeconfig.

## Kubefirst version

Definitely appears in v2.4.13 of Kuberfirst. Was introduced in [v0.1.25 of API](https://github.com/kubefirst/kubefirst-api/releases/tag/v0.1.25)

## Steps to reproduce

- Deploy from either command line or UI

## Suggested fix

I think there's a few things that need to happen.

### Fixing the immediate problem

The immediate problem is that our published version does not work for multiple cloud providers. I would suggest reverting #363 and then publishing a new version. This should at least solve the urgency of the problem

### Fixing the timeout issue in ArgoCD deployment

This is the issue that was being looked at in the original PR. I don't know enough about the problem to be certain, but doing a rollout deployment, retrying and waiting _feels_ a bit like we're addressing the symptoms of the problem rather than addressing the problem itself. I am available for pairing on this to help debug this problem.

If it is indeed the case that this is the only way the problem can be solved (which is fine) then it should use the existing [client-go](https://github.com/kubernetes/client-go) configuration rather than using `kubectl`. `client-go` is used extensively in Kubefirst-API so I expect that this would be using the correct configuration, regardless of cloud provider.

**NB.** `client-go` doesn't have a `rollout restart` command, so the likely scenario would be adding an annotation to the deployment (see [SO](https://stackoverflow.com/questions/61335318/how-to-restart-a-deployment-in-kubernetes-using-go-client)). This is the accepted way of forcing a restart of the pod.

### PR DESCRIPTION
**Pull request by jokestax**
## Description

Replaced kubectl with client go to reload the argocd-applicationset-controller which sometimes starts before repo server and gives secret key missing which leads to timeout issue

## Related Issue(s)

Fixes #376 

## How to test

Clone this repo  and kubefirst repo locally,checkout branch "client" on api repo and in the go mod file of kubefirst add this line "replace github.com/kubefirst/kubefirst-api v0.1.26 => PATH-TO-KUBEFIRST-API" ,replace PATH-TO-KUBEFIRST-API with actual path

### CODE REVIEW

**Comment by mrsimonemms** [comment]
@jokestax can you provide some context to the PR please? The default format should have the following information which will help me review it accurately (please let me know if it's not been included).

```
## Description
<!-- Describe your changes in detail -->

## Related Issue(s)
<!-- List the issue(s) this PR solves. An issue should be raised before creating a PR -->
Fixes #

## How to test
<!-- Provide steps to test this PR -->
```

**Review by mrsimonemms — CHANGES_REQUESTED** [review]
@jokestax can you provide some context to the PR please? The default format should have the following information which will help me review it accurately (please let me know if it's not been included).

```
## Description
<!-- Describe your changes in detail -->

## Related Issue(s)
<!-- List the issue(s) this PR solves. An issue should be raised before creating a PR -->
Fixes #

## How to test
<!-- Provide steps to test this PR -->
```

I would also suggest that you return the `Dockerfile` to [it's original state](https://github.com/kubefirst/kubefirst-api/pull/363/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557) as `kubectl` shouldn't be in there now

File: internal/controller/argocd.go [hunk 1]
```diff
@@ -150,6 +150,31 @@ func (clctrl *ClusterController) InitializeArgoCD() error {
 	return nil
 }
 
+
+func RestartDeployment(ctx context.Context,clientset *kubernetes.Clientset,namespace string,deployment_name string) error {
```
Comment (patrickdappollonio) [inline internal/controller/argocd.go]: It would be good to have a unit test for `RestartDeployment` so if someone like me were to go modify the function, I don't break your work.

File: internal/controller/argocd.go [hunk 2]
```diff
@@ -150,6 +150,31 @@ func (clctrl *ClusterController) InitializeArgoCD() error {
...
+
+	deploy.Spec.Template.ObjectMeta.Annotations["kubectl.kubernetes.io/restartedAt"] = time.Now().Format(time.RFC3339)
+
+	_,err = clientset.AppsV1().Deployments(namespace).Update(ctx,deploy,metav1.UpdateOptions{})
+	
+	if err != nil {
+		return err
+	}
+
+	return nil
```
Comment (patrickdappollonio) [inline internal/controller/argocd.go]:
```suggestion
	_,err = clientset.AppsV1().Deployments(namespace).Update(ctx,deploy,metav1.UpdateOptions{})

	if err != nil {
		return fmt.Errorf("unable to update deployment %q: %w", deploy, err)
	}

	return nil
```

I'm down to add some more context to this error just in case the original error doesn't include enough context.

**Review by patrickdappollonio — CHANGES_REQUESTED** [review]
Great work 😄 Left you some of the nitpicks I chatted with you about.

File: internal/controller/argocd.go (hunk 1 above)
Comment (mrsimonemms) [reply internal/controller/argocd.go]: We do need to check that our CI/CD pipelines actually run tests. I can't see anything in the `.github/workflows` folder with `go test` (or similar)

I would suggest creating the test as part of this PR and then doing a separate ticket/PR to implement that

Comment (patrickdappollonio) [reply internal/controller/argocd.go]: To avoid scope creeping @jokestax (and because he's probably already past biz hours) I'm happy to take that part of allowing unit tests to run.

**Comment by jokestax** [comment]
Edited the Dockerfile Simon :)

File: internal/controller/argocd.go (hunk 1 above)
Comment (jokestax) [reply internal/controller/argocd.go]: Added unit test and rebased

**Comment by fharper** [comment]
Would it be possible to prioritize testing this PR and releasing a new version when merged please? Our users are having this issue :)

**Review by mrsimonemms — APPROVED** [review]
