### PR TITLE
fix(azure): make the dns resource group optional

### LINKED ISSUE #2337: Make API so that Azure DNS resource group is an optional parameter
See parent issue for detail

### PR DESCRIPTION
**Pull request by mrsimonemms**
## Description

Make the Azure DNS resource group optional

## Related Issue(s)

Fixes https://github.com/konstructio/kubefirst/issues/2337

## How to test

See https://github.com/konstructio/kubefirst/pull/2339

### CODE REVIEW

File: internal/azure/azure.go [hunk 1]
```diff
@@ -163,6 +163,50 @@ func (c *Client) GetStorageAccessKeys(ctx context.Context, resourceGroup, storag
...
+	// Search through resource groups and return true for first match
+	for _, resourceGroup := range groups {
+		name := resourceGroup.Name
+		hasDomain, err := c.TestHostedZoneLiveness(ctx, domainName, *name)
+		if err != nil {
+			return false, nil, err
+		}
+
+		if hasDomain {
+			return true, name, err
```
Comment (jokestax) [inline internal/azure/azure.go]: it should be ?
```bash
return true, name,nil
```

File: internal/azure/azure.go [hunk 2]
```diff
@@ -163,6 +163,50 @@ func (c *Client) GetStorageAccessKeys(ctx context.Context, resourceGroup, storag
...
+		}
+	}
+
+	return false, nil, nil
```
Comment (jokestax) [inline internal/azure/azure.go:207]: this should return an error ?
```bash 
return false, nil,fmt.Errorf("failed to find zoneliveliness")
```

File: internal/azure/azure.go [hunk 3]
```diff
@@ -163,6 +163,50 @@ func (c *Client) GetStorageAccessKeys(ctx context.Context, resourceGroup, storag
...
+	groups, err := c.ListResourceGroups(ctx)
+	if err != nil {
+		return false, nil, err
+	}
+
+	// Search through resource groups and return true for first match
+	for _, resourceGroup := range groups {
+		name := resourceGroup.Name
+		hasDomain, err := c.TestHostedZoneLiveness(ctx, domainName, *name)
+		if err != nil {
```
Comment (jokestax) [inline internal/azure/azure.go:198]: we need to test for all domains and should continue if we didn't find for first one ,this should be removed ?

File: internal/azure/azure.go [hunk 4]
```diff
@@ -163,6 +163,50 @@ func (c *Client) GetStorageAccessKeys(ctx context.Context, resourceGroup, storag
...
+		groups = append(groups, page.Value...)
+	}
+
+	return groups, nil
+}
+
+func (c *Client) TestHostedZoneLivenessWildcard(ctx context.Context, domainName string) (bool, *string, error) {
+	groups, err := c.ListResourceGroups(ctx)
+	if err != nil {
+		return false, nil, err
```
Comment (jokestax) [inline internal/azure/azure.go:191]:
```bash
return false,nil,fmt.Errorf("failed to list resource groups: %w",err)
```

**Review by jokestax — CHANGES_REQUESTED** [review]

File: internal/azure/azure.go (hunk 4 above)
Comment (mrsimonemms) [reply internal/azure/azure.go:191]: No need. The `c.ListResourceGroups` function already has that in - see line 179

File: internal/azure/azure.go (hunk 1 above)
Comment (mrsimonemms) [reply internal/azure/azure.go]: Good spot

File: internal/azure/azure.go (hunk 2 above)
Comment (mrsimonemms) [reply internal/azure/azure.go:207]: No, there is no error - that's why the first parameter returns `false`

File: internal/azure/azure.go (hunk 3 above)
Comment (mrsimonemms) [reply internal/azure/azure.go:198]: I don't quite understand what you mean here - please explain further

Comment (jokestax) [reply internal/azure/azure.go:198]: as we are searching for first true ,we should not return false if we there was an error for some group, we should return false once we have checked for all groups

**Review by jokestax — CHANGES_REQUESTED** [review]

File: internal/azure/azure.go (hunk 3 above)
Comment (mrsimonemms) [reply internal/azure/azure.go:198]: Unless I change the type to `*bool` (which I don't want to do), I can only return `true` or `false` - the previous [iteration of this](https://github.com/konstructio/kubefirst-api/blob/main/internal/azure/azure.go#L175) returned `bool`.

If it errors, we should short-circuit because we're not getting all the data.

**Review by jokestax — APPROVED** [review]
